openapi: 3.0.0
info:
  title: FeastSync Booking App API
  version: 1.0.0
  description: API documentation for the FeastSync Booking App, which allows users to book a vendor's services
paths:
  /api/v1/bookings/bookings:
    post:
      summary: this is the endpoint for creating a new booking
      tags: [bookings]
      security:
        - bearerAuth: []
          name: Authorization
          in: headers
      requestBody:
        required: true
        content: 
          multipart/form-data:
            schema:
              type: object
              required:
                - pricingId
                - vendorId
                - eventDate
                - eventType
                - eventLocation
                - duration
                - guestCount
                - additionalDetails
              properties:
                pricingId:
                  type: string
                  description: The ID of the pricing package
                vendorId:
                  type: string
                  description: The ID of the vendor
                eventDate:
                  type: string
                  format: date
                  description: The date of the event
                duration:
                  type: string
                  enum: [2 hours, 4 hours, 6 hours, 8 hours, full day]
                  description: The duration of the event
                eventType:
                  type: string
                  enum: [wedding, birthday party, corporate event, product launch, cultural festival, anniversary, graduation, burial]
                  description: The type of the event
                eventLocation:
                  type: string
                  description: The location of the event
                guestCount: 
                  type: string
                  enum: [50-100, 100-200, 200-300, 300-400, 400-500, 600+]
                  description: The number of guests for the event
                additionalDetails: 
                  type: string
                  description: Further information that is required    
      responses:          
        '201':
          description: Booking created successfully

  
  /api/v1/bookings/booking-details/{bookingId}:
    get:
      summary: this is the endpoint to get booking details
      tags: [bookings]
      parameters: 
        - in: path
          name: bookingId 
      responses:          
        "200":
          description: Booking accepted successfully 
        "500": 
          description: Something went wrong 
          

  /api/v1/bookings/accept/{bookingId}:
    put:
      summary: this is the endpoint for accepting a new booking
      tags: [bookings]
      security:
        - bearerAuth: []
          name: Authorization
          in: headers
      parameters: 
        - in: path
          name: bookingId 
      responses:          
        "200":
          description: Booking accepted successfully 
        "500": 
          description: Something went wrong         

  /api/v1/bookings/reject/{bookingId}:
    put:
      summary: this is the endpoint for rejecting a new booking
      tags: [bookings]
      security:
        - bearerAuth: []
          name: Authorization
          in: headers
      parameters: 
        - in: path
          name: bookingId 
      responses:          
        "200":
          description: Booking reject successfully 
        "500": 
          description: Something went wrong  

  /api/v1/confirm-booking/{bookingId}:
    put:
      summary: User confirms that the vendor completed the event
      tags: [bookings]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: bookingId
          required: true
          schema:
            type: string
          description: Booking ID
      responses:
        '200':
          description: Event confirmed and escrow released successfully
        '400':
          description: Event already confirmed
        '404':
          description: Booking not found
        '500':
          description: Server error  

  /api/v1/complete-task/{bookingId}:
    put:
      summary: Vendor marks to have completed task for the event
      tags: [bookings]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: bookingId
          required: true
          schema:
            type: string
          description: Booking ID
      responses:
        '200':
          description: Event confirmed and escrow released successfully
        '400':
          description: Event already confirmed
        '404':
          description: Booking not found
        '500':
          description: Server error             

  /api/v1/bookings/vendor/{vendorId}:
    get:
      summary: this is the endpoint for fetching all vendors bookings
      tags: [bookings]
      parameters: 
        - in: path
          name: vendorId 
      responses:          
        "200":
          description: All vendors bookings fetched successfully 
        "500": 
          description: Something went wrong                       