openapi: 3.0.0
info:
  title: FeastSync Booking App API
  version: 1.0.0
  description: API documentation for the FeastSync Booking App, which allows vendors upload their government approved means of Identification.
paths:
  /api/v1/kyc/upload-kyc:
    post: 
      summary: this is the endpoint for KYC verification upload
      tags: [kyc]
      security:
        - bearerAuth: []
          name: Authorization
          in: headers 
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - documentImage
              properties:
                documentImage: 
                  type: string
                  format: binary
                  description: The vendor's government approved identity card   
      responses:          
        '201':
          description: KYC uploaded successfully
        '500': 
          description: Something went wrong        


        

