openapi: 3.0.0
info:
  title: FeastSync Booking App API
  version: 1.0.0
  description: API documentation for the FeastSync Booking App, which allows users to make payments to vendors for different events.
paths:
  /api/v1/payment/initialize-payment/{vendorId}/{bookingId}:
    post: 
      summary: this is the endpoint for initializing a payment
      tags: [payments]
      security:
        - bearerAuth: []
          name: Authorization
          in: headers
      parameters:
        - in: path
          name: vendorId
          required: true

        - in: path
          name: bookingId
          required: true  
      responses:          
        '201':
          description: Payment initialized successfully
        '500': 
          description: Something went wrong

          
  /api/v1/payment/all-payments:
    post: 
      summary: this is the endpoint for initializing a payment
      tags: [payments]
      security:
        - bearerAuth: []
          name: Authorization
          in: headers
      responses:          
        '200':
          description: Payment initialized successfully
        '500': 
          description: Something went wrong


