openapi: 3.0.0
info:
  title: FeastSync Booking App API
  version: 1.0.0
  description: API documentation for the FeastSync Booking App, which allows users to book vendors for different events.
paths:
  /api/v1/user/register:
    post: 
      summary: this is the endpoint for user registration
      tags: [users]
      requestBody:
        required: true
        content: 
          application/json:
          schema:
            type: object
            required:
              - firstName
              - lastName
              - email
              - password
              - confirmPassword  
            propertiies:
              firstName:
                type: string
                description: The user's first name
              lastName:
                type: string
                description: The user's last name
              email:
                type: string
                description: The user's email address
              password:
                type: string
                description: The user's password
              confirmPassword:
                type: string
                description: Confirmation of the user's password  
      responses:          
        '201':
          description: User created successfully


          
  /api/v1/user/verify:
    post: 
      summary: this is the endpoint for user verification
      tags: [users]
      requestBody:
        required: true
        content: 
          application/json:
          schema:
            type: object
            required:
              - email
              - otp  
            propertiies:
              email:
                type: string
                description: The user's email address
              otp:
                type: string
                description: The one-time password for verification
      responses:
        '201':
          description: User verified successfully

          
  /api/v1/user/login:
    post: 
      summary: this is the endpoint for user login
      tags: [users]
      requestBody:
        required: true
        content: 
          application/json:
          schema:
            type: object
            required:
              - email
              - password
            propertiies:
              email:
                type: string
                description: The user's email address
              password:
                type: string
                description: The user's password
      responses:          
        '201':
          description: User logged in successfully

          
  /api/v1/user/forgot-password:
    post: 
      summary: this is the endpoint for forgot password
      tags: [users]
      requestBody:
        required: true
        content: 
          application/json:
          schema:
            type: object
            required:
              - email
            propertiies:
              email:
                type: string
                description: The user's email address 
      responses:          
        '201':
          description: Forgot password request submitted successfully

          
  /api/v1/user/reset-password:
    post: 
      summary: this is the endpoint for resetting password  
      tags: [users]
      requestBody:
        required: true
        content: 
          application/json:
          schema:
            type: object
            required:
              - email
              - password
              - confirmPassword
            propertiies:
              email:
                type: string
                description: The user's email address
              password:
                type: string
                description: The user's password 
              confirmPassword:
                type: string
                description: Confirmation of the user's password
      responses:          
        '201':
          description: User's password reset successfully

          
  /api/v1/user/change-password:
    post: 
      summary: this is the endpoint for changing password
      tags: [users]
      requestBody:
        required: true
        content: 
          application/json:
          schema:
            type: object
            required:
              - email
              - password
              - confirmPassword  
            propertiies:
              email:
                type: string
                description: The user's email address
              password:
                type: string
                description: The user's password
              confirmPassword:
                type: string
                description: Confirmation of the user's password  
      responses:          
        '201':
          description: User's password changed successfully


